<?php
namespace Aura\Marshal;
use Aura\Marshal\Entity\GenericEntity;
use Aura\Marshal\MockType;

/**
 * Test class for Entity.
 * Generated by PHPUnit on 2011-11-26 at 14:30:57.
 */
class EntityTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var GenericEntity
     */
    protected $entity;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $data = [
            'foo' => 'bar',
            'baz' => 'dim',
            'zim' => 'gir',
            'numeric' => '123',
            'zero' => 0,
            'falsy' => false,
            'nully' => null,
            'related' => 'related_entity',
        ];
        
        $type = new MockType;
        
        // add a fake relation so we can check changes on relationships
        $type->addFakeRelation('related');
        
        $this->entity = new GenericEntity($data, $type);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }
    
    public function testSetAndGet()
    {
        $this->entity->irk = 'doom';
        $this->assertSame('doom', $this->entity->irk);
    }
    
    public function testIssetAndUnset()
    {
        $this->assertTrue(isset($this->entity->foo));
        unset($this->entity->foo);
        $this->assertFalse(isset($this->entity->foo));
        
        $this->assertFalse(isset($this->entity->newfield));
        
        $this->entity->newfield = 'something';
        $this->assertTrue(isset($this->entity->newfield));
        
        unset($this->entity->newfield);
        $this->assertFalse(isset($this->entity->newfield));
    }
}
